steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: Installing NPM
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: BUILDING WITH NPM
    args: ['run', 'build']

  - name:  'gcr.io/cloud-builders/npm'
    id: UNIT TESTING
    args: ['install', '-g', 'karma-cli', 'run', 'test']

  - name: 'gcr.io/$PROJECT_ID/sonar-scanner:latest'
    id: Sonarqube Integration - code quality inspection
    args:
      - '-Dsonar.host.url=https://sonarcloud.io'
      - '-Dsonar.login=$_SONAR_LOGIN'
      - '-Dsonar.projectKey=$_SONAR_PROJECT'
      - '-Dsonar.organization=$_SONAR_ORG'
      - '-Dsonar.sources=.'  
    
  
