steps:
  - name: 'gcr.io/cloud-builders/npm'
    id: Installing NPM
    args: ['install']

  - name: 'gcr.io/cloud-builders/npm'
    id: BUILDING WITH NPM
    args: ['run', 'build']

  - name:  'gcr.io/cloud-builders/npm'
    id: UNIT TESTING
    args: ['install', '-g', 'karma-cli', 'run', 'test']
    
  - name: 'gcr.io/cloud-builders/npm'
    entrypoint: npm
    args: ['-Dsonar.host.url=https://sonarcloud.io','-Dsonar.organization=sushil-demo-nest-run','-Dsonar.projectKey=sushil-demo-nest-run-project','-Dsonar.login=${_SONAR_TOKEN}']
